module.exports = {
    GAME_STATUS_NEW: 'new',
    GAME_STATUS_STARTED: 'started',
    GAME_STATUS_ENDED: 'ended',

    CARD_ARMOR: 'armor',
    CARD_KEY: 'key',
    CARD_SCANNER: 'scanner',
    CARD_GRENADE: 'grenade',
    CARD_GAS: 'gas',
    CARD_FIRST_AID: 'firstAid',
    CARD_TARGET_SCOPE: 'targetScope',
    CARD_KNIFE: 'knife',
    CARD_GUN: 'gun',
    CARD_AMMO: 'ammo',
    CARD_ENERGY: 'energy',
    CARD_PARASITE: 'parasite',
    CARD_BLOOD: 'blood',
    CARD_INFECTION: 'infection',

    ROOM_RUN: 'run',
    ROOM_TEAM_SEARCH: 'teamSearch',
    ROOM_STORAGE: 'storage',
    ROOM_PARASITE: 'parasite',
    ROOM_EMPTY: 'empty',
    ROOM_TERMINAL: 'terminal',
    ROOM_HEAL: 'heal',
    ROOM_HIVE: 'hive',
    ROOM_REACTOR: 'reactor',

    ROOM_SIDE_TYPE_WALL: 'wall',
    ROOM_SIDE_TYPE_DOOR: 'door',
    ROOM_SIDE_TYPE_LOCKED: 'locked',

    SIDES: {
        1: 'top',
        2: 'right',
        3: 'bottom',
        4: 'left',
    },
    ORTHOGONALS_TO_SIDES: [1, 4, 2, 3],
};
